# Generated by Django 4.0.4 on 2025-02-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planetariumdome",
            old_name="seat",
            new_name="rows",
        ),
    ]
